name: Particles
version: '${project.version}'
main: bgprotobg.net.particles.Particles
api-version: '1.20'
commands:
  trails:
    description: Opens the particle trails GUI.
    usage: /<command>

permissions:
  some_permission:
    description: Permission to use a specific particle effect.
    default: op